# Generated by Django 3.1.4 on 2020-12-11 08:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sanitaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanitaire',
            name='name',
            field=models.CharField(default=datetime.datetime(2020, 12, 11, 8, 56, 54, 317391, tzinfo=utc), max_length=30),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
