# Generated by Django 3.1.4 on 2020-12-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitaires', '0002_auto_20201211_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichierFrais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('message_frais', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Sanitaire',
        ),
    ]
