# Generated by Django 3.1.4 on 2020-12-19 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitaires', '0003_auto_20201215_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichierfrais',
            name='message_frais',
            field=models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])]),
        ),
    ]
