# Generated by Django 3.1.4 on 2020-12-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanitaires', '0004_auto_20201219_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichierfrais',
            name='titre',
        ),
        migrations.RemoveField(
            model_name='fichierfrais',
            name='uploaded_at',
        ),
    ]
